[tools]
lefthook = "2.1.1"
stylua = "2.5.2"

[hooks]
postinstall = "lefthook install"

[vars]
dst_steam_path = "$HOME/.local/share/Steam/steamapps/common/Don't Starve Together"
dst_steam_mod_location = "{{vars.dst_steam_path}}/mods/dst-omnikey"
dst_steam_scripts_location = "{{vars.dst_steam_path}}/data/databundles/scripts.zip"


[tasks]
extract = '''
rm -rf dst-scripts-original
mkdir -p dst-scripts-original
unzip -o -q "{{vars.dst_steam_scripts_location}}" -d dst-scripts-original
'''
